### ISSUE TITLE
What about "--" to separate positional arguments?

### ISSUE THREAD

**Issue by Bronek** [kongaskristjan/fire-hpp#1]
Ideally a command line parsing library should support `--` to separate positional arguments from options., to support CLI interface like this:

```
$ touch -- -actual-file-with-dash-prefix
$ ls -l -- -actual-file-with-dash-prefix
-rw-r--r-- 1 bronek users 0 Aug  8 19:03 -actual-file-with-dash-prefix
$ rm -- -actual-file-with-dash-prefix
```

BTW, this is lovely library, thank you for doing it!

**Comment by kongaskristjan** [comment]
Fixed in 95a7587!
