### ISSUE TITLE
Downloading the project (gtest) is unsafe unless you store and verify the cryptographic hash

### ISSUE THREAD

**Issue by yurivict** [kongaskristjan/fire-hpp#11]
Here: https://github.com/kongaskristjan/fire-hpp/blob/master/tests/CMakeLists.txt#L10

git protocol doesn't guarantee that actual downloaded file corresponds to the requested tag. Malicious git server can easily return a malicious file instead.

Please either ensure that the cryptographic hash (fingerprint) is verified, or use a pre-installed gtest.

**Comment by kongaskristjan** [comment]
Fixed in 8753e2be2711959a8ed46aba5581f35f0b115e35
