### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fjp** [kongaskristjan/fire-hpp#12]
Hi @kongaskristjan, thanks for the great work on this project!

Is the project still maintained? I noticed that the last official release 0.2 was in 2020, and since then, several valuable features have been added, including the constraints feature, but haven't been released yet.

Do you have any plans for a new release that incorporates the latest features? It would be great to hear about any potential timeline, or if there are any ways the community can assist in preparing for the next release.

Thanks again for your time and effort in maintaining the project!

**Comment by kongaskristjan** [comment]
Hey @fjp, thanks for the nudge! Yeah, I think this project has been mature for quite a long time now, so a `v1.0` would make sense. I actually forgot that some unreleased features are just pending on the master branch. I'll try to make the release next weekend or so.

Regarding the future of this project, I'm currently not planning to add any new features, though I still hope to fix bugs and support latest C++ versions/compilers.

**Comment by kongaskristjan** [comment]
Hey, just released `v1.0`.
