### ISSUE TITLE
The description string does not work as documented

### ISSUE THREAD

**Issue by JeffIrwin** [kongaskristjan/fire-hpp#2]
When I provide a help description string, it is used as a default instead of a description:

    int fired_main(std::string file = fire::arg(0, "<first>"))

When I run this as of commit 2a562ff, I get:

    $ ./build/colormapper.exe --help

    Usage:
      C:\git\maph\submodules\colormapper\build\colormapper.exe [<0>]

    Options:
      [<0> STRING]   [default: <first>]

`<first>` becomes the default value instead of the description.  I tried this with an `int` positional argument as well `std::string` and it has the same problem.

Thank you for the header!  This is an interesting project and it looks promising to reduce boilerplate.

**Comment by kongaskristjan** [comment]
Indeed, there are currently bugs in the documentation and the logic is not very well explained. I'll look into it later today.

For the fire::arg constructor, the first argument is always the name/position/description etc. Second argument is the default value. If you need to specify for example the position, name and description, add braces around the first argument:

`int fired_main(std::string file = fire::arg({0, "<name of argument>", "description of argument"}))`

First argument elements are interpreted according to this logic:

- `"-s"` shorthand name for argument
- `"--multicharacter-name"`
- `0` index in positional argument
- `"<name of the positional argument>"`
- everything else: `"description of any argument"`

**Comment by kongaskristjan** [comment]
Fixed the doc in 10c1d57a2f0f8746390b964890ebd49bfdd7f062

**Comment by JeffIrwin** [comment]
Thank you!  I forgot to use braces `{}` when I tried this earlier.  In any case, the documentation is clear now.
